library(GEOquery)
library(glmnet)
library(illuminaHumanv4.db)
library(matrixStats)
library(e1071)
library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization

#following the R script generated by GEO2R on the GSE47598 page
#fetch the data matrix from GEO.  This contains a bunch of stuff including the expression for each gene/individual.
gse <- getGEO("GSE47598", GSEMatrix = TRUE) 

#I believe this is formatting to make the gse list convertible later with the exprs function
if (length(gse) > 1) idx <- grep("GPL10558", attr(gse, "names")) else idx <- 1
gse <- gse[[idx]]

show(gse)

#This is the classification vector (0 means patient, 1 is control)
y = c(0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1)

#Convert the GSE list into a matrix (and traspose so rows are individuals (sample) and columns are genes (features).
eset <- t(exprs(gse))

rm(gse)

#coefficient of varaition
CoVar.geo = colSds(eset,cols = 1:ncol(eset))/colMeans(eset)

spats2l <- which(colnames(eset)=="ILMN_1683678")
klf6 <- which(colnames(eset)=="ILMN_1735014")
sp140 <- which(colnames(eset)=="ILMN_1703263")
rora <- which(colnames(eset)=="ILMN_2322498")


#spats2l is 6963

#eset, which is the matrix we are interested in in huge so viewing it all takes forever in R.  This just
# let me verify that the data matches the GSM files
show(eset[,c(spats2l,klf6,sp140,rora)])
show(CoVar.geo[,c(spats2l,klf6,sp140,rora)])

#Initialize
x <- eset
x[is.na(x)] = 0

#distance
distance_Euclid <- get_dist(x, method = "euclidean")
distance_Manhattan <- get_dist(x, method = "manhattan")
fviz_dist(distance_Euclid, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
fviz_dist(distance_Manhattan, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

#Kmeans
K2 <- kmeans(x, centers = 2, nstart = 100)
#notice that clusters were found of size 9 and 15
str(K2)
fviz_cluster(K2, data = x)
#originally 29.17 percent of patients didn't have psoriasis
#in cluster 1, that is 33.33
mean(y[K2$cluster == 1])
#in cluster 2, that is  26.67
mean(y[K2$cluster == 2])
#Therefore this doesn't seem to be clustering on the disease

#supposing we looked at more than two clusters.  Will any of them do better?
for (NumClusters in c(2, 3,4,5,6,7,8)){
  Ktest <- kmeans(x, centers = NumClusters, nstart = 50)
  print(paste("Number of Cluster : ", NumClusters))
  for (ii in 1:NumClusters){
    print(paste("Cluster: ",ii,
                "   mean: ", mean(y[Ktest$cluster == ii]), 
                cat("     Actual: ", y[Ktest$cluster == ii])))
  }
  print('===========================')
}

      