library(GEOquery)
library(glmnet)
library(leaps)
library(illuminaHumanv4.db)

#following the R script generated by GEO2R on the GSE47598 page
#fetch the data matrix from GEO.  This contains a bunch of stuff including the expression for each gene/individual.
gse <- getGEO("GSE47598", GSEMatrix = TRUE) 

#I believe this is formatting to make the gse list convertible later with the exprs function
if (length(gse) > 1) idx <- grep("GPL10558", attr(gse, "names")) else idx <- 1
gse <- gse[[idx]]

show(gse)

#This is the classification vector (0 means patient, 1 is control)
y = c(0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1)

#Convert the GSE list into a matrix (and traspose so rows are individuals (sample) and columns are genes (features).
eset <- t(exprs(gse))

rm(gse)


#eset, which is the matrix we are interested in in huge so viewing it all takes forever in R.  This just
# let me verify that the data matches the GSM files
show(eset[,1:5])

teset <- cbind(y,eset)
show(teset[,1:5])

#lasso
grid =10^seq(10,-2, length = 13)
lasso.geo = glmnet(eset,y, family = 'binomial',alpha = 1, lambda = grid)

summary(lasso.geo)

#forward stepwise

teset.df = as.data.frame(teset)
regfit.geo = regsubsets(y~.,data=teset.df,nvmax=10,method='forward')
summary(regfit.geo)

