library(GEOquery)
library(glmnet)
library(illuminaHumanv4.db)
library(matrixStats)
library(graphics)
library(boot)


rm(list=ls())
cat("\014")

#following the R script generated by GEO2R on the GSE47598 page
#fetch the data matrix from GEO.  This contains a bunch of stuff including the expression for each gene/individual.
gse <- getGEO("GSE47598", GSEMatrix = TRUE) 

#I believe this is formatting to make the gse list convertible later with the exprs function
if (length(gse) > 1) idx <- grep("GPL10558", attr(gse, "names")) else idx <- 1
gse <- gse[[idx]]

#Convert the GSE list into a matrix (and traspose so rows are individuals (sample) and columns are genes (features).
eset <- t(exprs(gse))

rm(gse)

#spats2l is 6963

#This is the classification vector (0 means patient, 1 is control)
y =     c(0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1)

eset.log <- log(eset)

pr.out = prcomp(eset.log, scale. = TRUE)

summary(pr.out)

PC1.sorted = sort(abs(pr.out$rotation[,"PC1"]),decreasing = TRUE)
which(names(PC1.sorted) == "ILMN_1683678")


which(names(sort(abs(pr.out$rotation[,"PC1"]),decreasing = TRUE)) == "ILMN_1683678")

Cols=function(vec) {
  cols=rainbow(length(unique(vec)))
  return(cols[as.numeric(as.factor((vec)))]) 
}

#sort(abs(pr.out$rotation[,"PC2"]),decreasing = TRUE)[1:50]
#sort(abs(pr.out$rotation[,"PC3"]),decreasing = TRUE)[1:50]

sum.pr = summary(pr.out)

plot(sum.pr$importance[1,], type = 'o', pch = 1, xlab = 'PC', ylab = 'Stdev')
plot(sum.pr$importance[2,], type = 'o', pch = 1, xlab = 'PC', ylab = 'PVE')
plot(sum.pr$importance[3,], type = 'o', pch = 1, xlab = 'PC', ylab = 'Cummulative PVE')

plot(pr.out$x[,c(1,2)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(1,3)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(1,4)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(1,5)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(1,6)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(1,7)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(1,8)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(1,9)],pch = 19, col=Cols(y))

plot(pr.out$x[,c(2,3)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(2,4)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(2,5)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(2,6)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(2,7)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(2,8)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(2,9)],pch = 19, col=Cols(y))

plot(pr.out$x[,c(3,4)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(3,5)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(3,6)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(3,7)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(3,8)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(3,9)],pch = 19, col=Cols(y))

plot(pr.out$x[,c(4,5)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(4,6)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(4,7)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(4,8)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(4,9)],pch = 19, col=Cols(y))

plot(pr.out$x[,c(5,6)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(5,7)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(5,8)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(5,9)],pch = 19, col=Cols(y))

plot(pr.out$x[,c(6,7)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(6,8)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(6,9)],pch = 19, col=Cols(y))

plot(pr.out$x[,c(7,8)],pch = 19, col=Cols(y))
plot(pr.out$x[,c(7,9)],pch = 19, col=Cols(y))

plot(pr.out$x[,c(8,9)],pch = 19, col=Cols(y))

#now try to use PCs to predict
data.pca <- data.frame(y=y, eset %*% pr.out$rotation[,1:10])
fit.pca <- glm(y ~.,data = data.pca, family = "binomial")
pred.pca <- predict(fit.pca, newdata = data.pca)

ypred <- (pred.pca < 0)

#LOOCV


ypred5.loocv =  ypred
data.pca <- data.frame(y=y, eset %*% pr.out$rotation[,1:5])
for(i in 1:24) {
  fit.pca <- glm(y ~.,data = data.pca[-i,], family = "binomial")
  pred.pca <- predict(fit.pca, newdata = data.pca[i,])
  ypred5.loocv[i] <- (pred.pca < 0)
}


ypred10.loocv =  ypred
data.pca <- data.frame(y=y, eset %*% pr.out$rotation[,1:10])
for(i in 1:24) {
  fit.pca <- glm(y ~.,data = data.pca[-i,], family = "binomial")
  pred.pca <- predict(fit.pca, newdata = data.pca[i,])
  ypred10.loocv[i] <- (pred.pca < 0)
}

ypred15.loocv =  ypred
data.pca <- data.frame(y=y, eset %*% pr.out$rotation[,1:15])
for(i in 1:24) {
  fit.pca <- glm(y ~.,data = data.pca[-i,], family = "binomial")
  pred.pca <- predict(fit.pca, newdata = data.pca[i,])
  ypred15.loocv[i] <- (pred.pca < 0)
}


ypred20.loocv =  ypred
data.pca <- data.frame(y=y, eset %*% pr.out$rotation[,1:20])
for(i in 1:24) {
  fit.pca <- glm(y ~.,data = data.pca[-i,], family = "binomial")
  pred.pca <- predict(fit.pca, newdata = data.pca[i,])
  ypred20.loocv[i] <- (pred.pca < 0)
}

show(ypred) 
show(ypred5.loocv) 
show(ypred10.loocv) 
show(ypred15.loocv) 
show(ypred20.loocv) 
 

