library(GEOquery)
library(glmnet)
library(illuminaHumanv4.db)
library(matrixStats)
library(MASS)

rm(list=ls())
cat("\014")

#following the R script generated by GEO2R on the GSE47598 page
#fetch the data matrix from GEO.  This contains a bunch of stuff including the expression for each gene/individual.
gse <- getGEO("GSE47598", GSEMatrix = TRUE) 

#I believe this is formatting to make the gse list convertible later with the exprs function
if (length(gse) > 1) idx <- grep("GPL10558", attr(gse, "names")) else idx <- 1
gse <- gse[[idx]]

#show(gse)
#This is the classification vector (0 means patient, 1 is control)
y =     c(0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1)
W
#Convert the GSE list into a matrix (and traspose so rows are individuals (sample) and columns are genes (features).
#eset, which is the matrix we are interested in in huge so viewing it all takes forever in R.  This just
# let me verify that the data matches the GSM files
eset <- t(exprs(gse))
show(eset[,1:5])

CoVar.geo = colSds(eset,cols = 1:ncol(eset))/colMeans(eset)
#take top 25% of genes with the most variation across samples as a first filter
filter.geo = which(CoVar.geo>quantile(CoVar.geo)[4])

eset.df <- as.data.frame(eset)
eset.filtered.df <- eset.df[,filter.geo]
yeset.filtered.df = (cbind(y,eset.filtered.df))

rm(gse)
rm(eset)
rm(eset.df)
rm(eset.filtered.df)

min.model <- glm(y ~ 1, family=binomial(link = 'logit'), data=yeset.filtered.df)
upper.model <- formula(glm(y~.,family = binomial(link = 'logit'), data = yeset.filtered.df))

fwd.geo <- step(min.model,scope = list(lower=min.model,upper=upper.model),direction = 'forward',steps = 10)